SET PASSWORD FOR 'root'@'localhost' = PASSWORD('');
CREATE DATABASE wordpress_db;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';
CREATE USER 'admin'@'localhost' IDENTIFIED BY PASSWORD '*4ACFE3202A5FF5CF467898FC58AAB1D615029441';
GRANT SELECT, INSERT, UPDATE, DELETE ON wordpress_db.* TO 'admin'@'localhost';
FLUSH PRIVILEGES;